export const fonts = [
  'Arial',
  'Helvetica',
  'Times New Roman',
  'Courier New',
  'Georgia',
  'Verdana',
  'Trebuchet MS',
  'Comic Sans MS',
  'Lucida Console',
  'Impact',
  'Garamond',
  'Palatino',
  'Tahoma',
  'Monaco',
  'Futura',
  'Baskerville',
  'Gill Sans',
  'Optima',
  'Franklin Gothic',
  'Candara',
  'Calibri',
  'Century Gothic',
];
export const fontWeight = [
  { label: 'Normal', value: '400' },
  { label: 'Bold', value: '700' },
  { label: 'Lighter', value: '300' },
  { label: 'Bolder', value: '900' },
  { label: 'Thin', value: '100' },
  { label: 'Extra Light', value: '200' },
  { label: 'Light', value: '300' },
  { label: 'Regular', value: '400' },
  { label: 'Medium', value: '500' },
  { label: 'Semi Bold', value: '600' },
  { label: 'Extra Bold', value: '800' },
  { label: 'Black', value: '900' },
];
